### ISSUE TITLE
Brak efektu z wykorzystaniem perspektywy

### ISSUE THREAD

**Issue by abadondev** [jedrzejchalubek/glidejs#159]
Czesc,

Dzięki za bardzo dobrą pracę. Chciałem Cię zapytać o układ slidera, który jest widoczny zaraz po wejściu na stronę wtyczki (z perspektywą). Nigdzie nie ma takich klas jak following, czy pre. Poszukuję własnie takiego efektu. Proszę o odpowiedź.

Pozdrawiam!

**Comment by jedrzejchalubek** [comment]
Jest to niestandardowy układ uzyskany poprzez API. Zwykłe nadawanie klas css, ktore określają przekrzywienie.

Poniżej kod prosto ze strony głównej.

```js
function coverflow(data) {
	data.current.removeClass('pre following')
		.nextAll()
			.removeClass('pre following')
			.addClass('following')
		.end()
		.prevAll()
			.removeClass('pre following')
			.addClass('pre');
}

$('#Glide').glide({
	type: 'slider',
	startAt: 3,
	autoplay: 3000,
	hoverpause: false,
	animationDuration: 500,
	paddings: '25%',
	afterInit: function (data) {
		coverflow(data);
	},
	afterTransition: function (data) {
		coverflow(data);
	}
});
```

```css
.pre { transform: perspective(60em) rotateY(18deg); }
.following { transform: perspective(60em) rotateY(-18deg); }
```
